{"version": "0.1", "tests": [{"id": "functional.test_toolbox.TestForTool_bowtie_rRNA_tRNA_removal_wrapper.test_tool_000000", "has_data": true, "data": {"tool_id": "bowtie_rRNA_tRNA_removal_wrapper", "tool_version": "1.4.0", "test_index": 0, "time_seconds": 0.028813838958740234, "execution_problem": "Input staging problem: Test input file (bowtie_in2.fastqsanger) cannot be found.", "status": "failure", "problem_type": "builtins.AssertionError", "problem_log": "  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 98, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 35, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1092, in verify_tool\n    stage_data_in_history(\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 81, in stage_data_in_history\n    upload_wait = galaxy_interactor.stage_data_async(test_data,\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 415, in stage_data_async\n    file_content = self.test_data_download(tool_id, fname, is_output=False, tool_version=tool_version)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 361, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nTest input file (bowtie_in2.fastqsanger) cannot be found.\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:69]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}, {"id": "functional.test_toolbox.TestForTool_bowtie_rRNA_tRNA_removal_wrapper.test_tool_000001", "has_data": true, "data": {"tool_id": "bowtie_rRNA_tRNA_removal_wrapper", "tool_version": "1.4.0", "test_index": 1, "time_seconds": 0.023845434188842773, "execution_problem": "Input staging problem: Test input file (phiX.fasta) cannot be found.", "status": "failure", "problem_type": "builtins.AssertionError", "problem_log": "  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 98, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 35, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1092, in verify_tool\n    stage_data_in_history(\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 81, in stage_data_in_history\n    upload_wait = galaxy_interactor.stage_data_async(test_data,\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 415, in stage_data_async\n    file_content = self.test_data_download(tool_id, fname, is_output=False, tool_version=tool_version)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 361, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nTest input file (phiX.fasta) cannot be found.\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:69]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}, {"id": "functional.test_toolbox.TestForTool_bowtie_rRNA_tRNA_removal_wrapper.test_tool_000002", "has_data": true, "data": {"tool_id": "bowtie_rRNA_tRNA_removal_wrapper", "tool_version": "1.4.0", "test_index": 2, "time_seconds": 0.01683974266052246, "execution_problem": "Input staging problem: Test input file (phiX.fasta) cannot be found.", "status": "failure", "problem_type": "builtins.AssertionError", "problem_log": "  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 98, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 35, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1092, in verify_tool\n    stage_data_in_history(\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 81, in stage_data_in_history\n    upload_wait = galaxy_interactor.stage_data_async(test_data,\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 415, in stage_data_async\n    file_content = self.test_data_download(tool_id, fname, is_output=False, tool_version=tool_version)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 361, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nTest input file (phiX.fasta) cannot be found.\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:69]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}, {"id": "functional.test_toolbox.TestForTool_bowtie_rRNA_tRNA_removal_wrapper.test_tool_000003", "has_data": true, "data": {"tool_id": "bowtie_rRNA_tRNA_removal_wrapper", "tool_version": "1.4.0", "test_index": 3, "time_seconds": 0.01752638816833496, "execution_problem": "Input staging problem: Test input file (phiX.fasta) cannot be found.", "status": "failure", "problem_type": "builtins.AssertionError", "problem_log": "  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 98, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 35, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1092, in verify_tool\n    stage_data_in_history(\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 81, in stage_data_in_history\n    upload_wait = galaxy_interactor.stage_data_async(test_data,\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 415, in stage_data_async\n    file_content = self.test_data_download(tool_id, fname, is_output=False, tool_version=tool_version)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 361, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nTest input file (phiX.fasta) cannot be found.\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:69]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}, {"id": "functional.test_toolbox.TestForTool_bowtie_rRNA_tRNA_removal_wrapper.test_tool_000004", "has_data": true, "data": {"tool_id": "bowtie_rRNA_tRNA_removal_wrapper", "tool_version": "1.4.0", "test_index": 4, "time_seconds": 0.028813600540161133, "execution_problem": "Input staging problem: Test input file (bowtie_in2.fastqsanger) cannot be found.", "status": "failure", "problem_type": "builtins.AssertionError", "problem_log": "  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 98, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 35, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1092, in verify_tool\n    stage_data_in_history(\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 81, in stage_data_in_history\n    upload_wait = galaxy_interactor.stage_data_async(test_data,\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 415, in stage_data_async\n    file_content = self.test_data_download(tool_id, fname, is_output=False, tool_version=tool_version)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 361, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nTest input file (bowtie_in2.fastqsanger) cannot be found.\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:69]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}, {"id": "functional.test_toolbox.TestForTool_bowtie_rRNA_tRNA_removal_wrapper.test_tool_000005", "has_data": true, "data": {"tool_id": "bowtie_rRNA_tRNA_removal_wrapper", "tool_version": "1.4.0", "test_index": 5, "time_seconds": 0.019893646240234375, "execution_problem": "Input staging problem: Test input file (phiX.fasta) cannot be found.", "status": "failure", "problem_type": "builtins.AssertionError", "problem_log": "  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 98, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 35, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1092, in verify_tool\n    stage_data_in_history(\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 81, in stage_data_in_history\n    upload_wait = galaxy_interactor.stage_data_async(test_data,\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 415, in stage_data_async\n    file_content = self.test_data_download(tool_id, fname, is_output=False, tool_version=tool_version)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 361, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nTest input file (phiX.fasta) cannot be found.\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:69]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}, {"id": "functional.test_toolbox.TestForTool_bowtie_rRNA_tRNA_removal_wrapper.test_tool_000006", "has_data": true, "data": {"tool_id": "bowtie_rRNA_tRNA_removal_wrapper", "tool_version": "1.4.0", "test_index": 6, "time_seconds": 0.01675868034362793, "execution_problem": "Input staging problem: Test input file (phiX.fasta) cannot be found.", "status": "failure", "problem_type": "builtins.AssertionError", "problem_log": "  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 592, in run\n    self._callTestMethod(testMethod)\n  File \"/home/jack/anaconda3/envs/ribogalaxy/lib/python3.9/unittest/case.py\", line 550, in _callTestMethod\n    method()\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 98, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/test/functional/test_toolbox.py\", line 35, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 1092, in verify_tool\n    stage_data_in_history(\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 81, in stage_data_in_history\n    upload_wait = galaxy_interactor.stage_data_async(test_data,\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 415, in stage_data_async\n    file_content = self.test_data_download(tool_id, fname, is_output=False, tool_version=tool_version)\n  File \"/tmp/tmpbm20a9vj/galaxy-dev/lib/galaxy/tool_util/verify/interactor.py\", line 361, in test_data_download\n    raise AssertionError(f\"Test input file ({filename}) cannot be found.\")\nTest input file (phiX.fasta) cannot be found.\n-------------------- >> begin captured logging << --------------------\nmultipart.multipart: DEBUG: Calling on_field_start with no data\nmultipart.multipart: DEBUG: Calling on_field_name with data[0:4]\nmultipart.multipart: DEBUG: Calling on_field_data with data[5:69]\nmultipart.multipart: DEBUG: Calling on_field_end with no data\nmultipart.multipart: DEBUG: Calling on_end with no data\n--------------------- >> end captured logging << ---------------------"}}], "summary": {"num_tests": 7, "num_failures": 7, "num_errors": 0, "num_skips": 0}, "exit_code": 1}